### ISSUE TITLE
Akvodev.org & akvouat.org robots.txt

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-provisioning#264] opened 2016-02-22 10:33 UTC
As per https://github.com/akvo/akvo-web/issues/152   robots.txt was previously setup to stop search engines crawling our test servers, yet akvodev.org & akvouat.org is being crawled by google regardless.

I checked akvodev.org but cannot find a robots.txt file  (or maybe my permissions don't allow me to see it) can someone please check this asap & if it is not set please block all search engines from crawling the test site.

**Comment by stellanl** [comment] 2016-02-22 15:22
I am pretty sure the name must be robots.txt (plural).

**Comment by Lynngre** [comment] 2016-02-22 16:11
Yes typo, robots.txt. Doing some Google webmaster testing but it's not reading the verification on the domain as yet.

**Comment by Lynngre** [comment] 2016-02-22 20:05
![screen shot 2016-02-22 at 21 03 40](https://cloud.githubusercontent.com/assets/2675262/13230958/cd18228a-d9a7-11e5-96ad-7c080949dcb2.png)

So robots.txt for akvodev.org is currently set to allow all to crawl.  This should be set to disallowed as before BUT akvo.org's robots.txt should NOT change during automated deployment (so this change should only affected akvodev.org).

**Comment by orifito** [comment] 2016-02-23 08:46
duplicate of #158, closing it

**Closed by orifito** 2016-02-23 08:46 UTC
